/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { CreatePlanDtoGoal } from './createPlanDtoGoal'

export interface CreatePlanDto {
  /** Start date of the plan */
  start_date: string
  /** Required for auto-calculation */
  goal?: CreatePlanDtoGoal
  /** Manual override for daily calories */
  day_calories?: number
  /** Manual override for daily protein (g) */
  day_protein?: number
  /** Manual override for daily fats (g) */
  day_fats?: number
  /** Manual override for daily carbs (g) */
  day_carbs?: number
}
