/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { CreateMealFoodDto } from './createMealFoodDto';

export interface CreateMealDto {
  name: string;
  date: string;
  mealFoods: CreateMealFoodDto[];
}
