/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

/**
 * Required for auto-calculation
 */
export type CreatePlanDtoGoal = typeof CreatePlanDtoGoal[keyof typeof CreatePlanDtoGoal];


export const CreatePlanDtoGoal = {
  maintain: 'maintain',
  gain: 'gain',
  lose: 'lose',
} as const;
