/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { PlanEntity } from './planEntity'

export interface DailyStatsEntity {
  date: string
  /** The active plan for this specific date, or null if none */
  plan?: PlanEntity | null
  /** Sum of all meals for this date */
  actual_calories: number
  actual_protein: number
  actual_fats: number
  actual_carbs: number
}
