/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

/**
 * The active plan for this specific date, or null if none
 * @nullable
 */
export type DailyStatsEntityPlan = { [key: string]: unknown } | null
