/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface LinkDeviceDto {
  /** The unique serial number of the IoT scale */
  serial_number: string
}
