/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { MealFoodEntity } from './mealFoodEntity';

export interface MealEntity {
  id: number;
  user_id: number;
  name: string;
  date: string;
  /** Sum of meal foods calories */
  calories: number;
  /** Sum of meal foods protein */
  protein: number;
  /** Sum of meal foods fats */
  fats: number;
  /** Sum of meal foods carbs */
  carbs: number;
  meal_foods: MealFoodEntity[];
}
