/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export type MealsControllerFindAllParams = {
/**
 * Start date (YYYY-MM-DD)
 */
start: string;
/**
 * End date (YYYY-MM-DD)
 */
end: string;
};
