/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface MeasurementEntity {
  id: number;
  user_id: number;
  date: string;
  /** Weight in kg */
  weight: number;
  /** Height in cm */
  height: number;
  /** Activity level */
  activity: number;
}
