/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export type PlanEntityPlan =
  (typeof PlanEntityPlan)[keyof typeof PlanEntityPlan]

export const PlanEntityPlan = {
  maintain: 'maintain',
  gain: 'gain',
  lose: 'lose',
} as const
