/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { PlanEntityPlan } from './planEntityPlan';

export interface PlanEntity {
  id: number;
  user_id: number;
  start_date: string;
  plan: PlanEntityPlan;
  day_calories: number;
  day_protein: number;
  day_fats: number;
  day_carbs: number;
}
