/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface ProductResponseDto {
  name: string;
  /** Kcal per 100g */
  calories: number;
  /** Protein per 100g */
  protein: number;
  /** Fats per 100g */
  fats: number;
  /** Carbs per 100g */
  carbs: number;
}
