/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  email: string;
  username: string;
  password: string;
  avatar_url?: string;
}
