/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface TemplateMealFoodEntity {
  id: number;
  template_meal_id: number;
  name: string;
  /** Weight in grams */
  weight: number;
  /** Calculated calories for the specific weight */
  calories: number;
  /** Calculated protein for the specific weight */
  protein: number;
  /** Calculated fats for the specific weight */
  fats: number;
  /** Calculated carbs for the specific weight */
  carbs: number;
}
