/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface TemplateFoodEntity {
  id: number;
  user_id: number;
  name: string;
  /** Per 100g or unit */
  calories: number;
  /** Per 100g or unit */
  protein: number;
  /** Per 100g or unit */
  fats: number;
  /** Per 100g or unit */
  carbs: number;
}
