/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

/**
 * Required for auto-calculation
 */
export type UpdatePlanDtoGoal =
  (typeof UpdatePlanDtoGoal)[keyof typeof UpdatePlanDtoGoal]

export const UpdatePlanDtoGoal = {
  maintain: 'maintain',
  gain: 'gain',
  lose: 'lose',
} as const
