/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export type UpdateUserDtoSex = typeof UpdateUserDtoSex[keyof typeof UpdateUserDtoSex];


export const UpdateUserDtoSex = {
  male: 'male',
  female: 'female',
} as const;
