/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { CreateTemplateMealFoodDto } from './createTemplateMealFoodDto'

export interface UpdateTemplateMealDto {
  name?: string
  templateMealFoods?: CreateTemplateMealFoodDto[]
}
