/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface UpdateTemplateFoodDto {
  name?: string;
  /** Calories per 100g or unit */
  calories?: number;
  /** Protein per 100g or unit */
  protein?: number;
  /** Fats per 100g or unit */
  fats?: number;
  /** Carbs per 100g or unit */
  carbs?: number;
}
