/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export interface UpdateMeasurementDto {
  /** Weight in kg */
  weight?: number;
  /** Height in cm */
  height?: number;
  /** Activity level */
  activity?: number;
  date?: string;
}
