/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoSex } from './updateUserDtoSex';

export interface UpdateUserDto {
  email?: string;
  username?: string;
  avatar_url?: string;
  sex?: UpdateUserDtoSex;
  /** ISO 8601 date string */
  date_of_birth?: string;
}
