/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */

export type UserEntitySex = (typeof UserEntitySex)[keyof typeof UserEntitySex]

export const UserEntitySex = {
  male: 'male',
  female: 'female',
} as const
