/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import type { UserEntitySex } from './userEntitySex';

export interface UserEntity {
  id: number;
  email: string;
  username: string;
  avatar_url?: string;
  sex?: UserEntitySex;
  date_of_birth?: string;
  device_serial_id?: string;
}
