/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTemplateMealDto,
  TemplateMealEntity,
  UpdateTemplateMealDto
} from '../../model';

import { customInstance } from '../../../lib/axios';
import type { ErrorType } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const templateMealsControllerFindAll = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TemplateMealEntity[]>(
      {url: `/templates/meals`, method: 'GET', signal
    },
      options);
    }




export const getTemplateMealsControllerFindAllQueryKey = () => {
    return [
    `/templates/meals`
    ] as const;
    }


export const getTemplateMealsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateMealsControllerFindAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateMealsControllerFindAll>>> = ({ signal }) => templateMealsControllerFindAll(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateMealsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof templateMealsControllerFindAll>>>
export type TemplateMealsControllerFindAllQueryError = ErrorType<unknown>


export function useTemplateMealsControllerFindAll<TData = Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof templateMealsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateMealsControllerFindAll<TData = Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof templateMealsControllerFindAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateMealsControllerFindAll<TData = Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTemplateMealsControllerFindAll<TData = Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateMealsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const templateMealsControllerCreate = (
    createTemplateMealDto: CreateTemplateMealDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TemplateMealEntity>(
      {url: `/templates/meals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateMealDto, signal
    },
      options);
    }



export const getTemplateMealsControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerCreate>>, TError,{data: CreateTemplateMealDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerCreate>>, TError,{data: CreateTemplateMealDto}, TContext> => {

const mutationKey = ['templateMealsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateMealsControllerCreate>>, {data: CreateTemplateMealDto}> = (props) => {
          const {data} = props ?? {};

          return  templateMealsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateMealsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof templateMealsControllerCreate>>>
    export type TemplateMealsControllerCreateMutationBody = CreateTemplateMealDto
    export type TemplateMealsControllerCreateMutationError = ErrorType<unknown>

    export const useTemplateMealsControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerCreate>>, TError,{data: CreateTemplateMealDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateMealsControllerCreate>>,
        TError,
        {data: CreateTemplateMealDto},
        TContext
      > => {
      return useMutation(getTemplateMealsControllerCreateMutationOptions(options), queryClient);
    }
    export const templateMealsControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TemplateMealEntity>(
      {url: `/templates/meals/${id}`, method: 'GET', signal
    },
      options);
    }




export const getTemplateMealsControllerFindOneQueryKey = (id: number,) => {
    return [
    `/templates/meals/${id}`
    ] as const;
    }


export const getTemplateMealsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError = ErrorType<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTemplateMealsControllerFindOneQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof templateMealsControllerFindOne>>> = ({ signal }) => templateMealsControllerFindOne(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateMealsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof templateMealsControllerFindOne>>>
export type TemplateMealsControllerFindOneQueryError = ErrorType<unknown>


export function useTemplateMealsControllerFindOne<TData = Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof templateMealsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateMealsControllerFindOne<TData = Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof templateMealsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTemplateMealsControllerFindOne<TData = Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTemplateMealsControllerFindOne<TData = Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof templateMealsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTemplateMealsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const templateMealsControllerUpdate = (
    id: number,
    updateTemplateMealDto: UpdateTemplateMealDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TemplateMealEntity>(
      {url: `/templates/meals/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTemplateMealDto, signal
    },
      options);
    }



export const getTemplateMealsControllerUpdateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerUpdate>>, TError,{id: number;data: UpdateTemplateMealDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerUpdate>>, TError,{id: number;data: UpdateTemplateMealDto}, TContext> => {

const mutationKey = ['templateMealsControllerUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateMealsControllerUpdate>>, {id: number;data: UpdateTemplateMealDto}> = (props) => {
          const {id,data} = props ?? {};

          return  templateMealsControllerUpdate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateMealsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof templateMealsControllerUpdate>>>
    export type TemplateMealsControllerUpdateMutationBody = UpdateTemplateMealDto
    export type TemplateMealsControllerUpdateMutationError = ErrorType<unknown>

    export const useTemplateMealsControllerUpdate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerUpdate>>, TError,{id: number;data: UpdateTemplateMealDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateMealsControllerUpdate>>,
        TError,
        {id: number;data: UpdateTemplateMealDto},
        TContext
      > => {
      return useMutation(getTemplateMealsControllerUpdateMutationOptions(options), queryClient);
    }
    export const templateMealsControllerRemove = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/templates/meals/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getTemplateMealsControllerRemoveMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['templateMealsControllerRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof templateMealsControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  templateMealsControllerRemove(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TemplateMealsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof templateMealsControllerRemove>>>

    export type TemplateMealsControllerRemoveMutationError = ErrorType<unknown>

    export const useTemplateMealsControllerRemove = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof templateMealsControllerRemove>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof templateMealsControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getTemplateMealsControllerRemoveMutationOptions(options), queryClient);
    }
