/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { LinkDeviceDto } from '../../model'

import { customInstance } from '../../../lib/axios'
import type { ErrorType } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const iotControllerLinkDevice = (
  linkDeviceDto: LinkDeviceDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/iot/scales/link`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: linkDeviceDto,
      signal,
    },
    options,
  )
}

export const getIotControllerLinkDeviceMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof iotControllerLinkDevice>>,
    TError,
    { data: LinkDeviceDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof iotControllerLinkDevice>>,
  TError,
  { data: LinkDeviceDto },
  TContext
> => {
  const mutationKey = ['iotControllerLinkDevice']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof iotControllerLinkDevice>>,
    { data: LinkDeviceDto }
  > = (props) => {
    const { data } = props ?? {}

    return iotControllerLinkDevice(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type IotControllerLinkDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof iotControllerLinkDevice>>
>
export type IotControllerLinkDeviceMutationBody = LinkDeviceDto
export type IotControllerLinkDeviceMutationError = ErrorType<unknown>

export const useIotControllerLinkDevice = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof iotControllerLinkDevice>>,
      TError,
      { data: LinkDeviceDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof iotControllerLinkDevice>>,
  TError,
  { data: LinkDeviceDto },
  TContext
> => {
  return useMutation(
    getIotControllerLinkDeviceMutationOptions(options),
    queryClient,
  )
}
export const iotControllerUnlinkDevice = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/iot/scales/link`, method: 'DELETE', signal },
    options,
  )
}

export const getIotControllerUnlinkDeviceMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof iotControllerUnlinkDevice>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof iotControllerUnlinkDevice>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['iotControllerUnlinkDevice']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof iotControllerUnlinkDevice>>,
    void
  > = () => {
    return iotControllerUnlinkDevice(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type IotControllerUnlinkDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof iotControllerUnlinkDevice>>
>

export type IotControllerUnlinkDeviceMutationError = ErrorType<unknown>

export const useIotControllerUnlinkDevice = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof iotControllerUnlinkDevice>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof iotControllerUnlinkDevice>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getIotControllerUnlinkDeviceMutationOptions(options),
    queryClient,
  )
}
export const iotControllerGetStatus = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/iot/scales/status`, method: 'GET', signal },
    options,
  )
}

export const getIotControllerGetStatusQueryKey = () => {
  return [`/iot/scales/status`] as const
}

export const getIotControllerGetStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof iotControllerGetStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof iotControllerGetStatus>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getIotControllerGetStatusQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof iotControllerGetStatus>>
  > = ({ signal }) => iotControllerGetStatus(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof iotControllerGetStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type IotControllerGetStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof iotControllerGetStatus>>
>
export type IotControllerGetStatusQueryError = ErrorType<unknown>

export function useIotControllerGetStatus<
  TData = Awaited<ReturnType<typeof iotControllerGetStatus>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof iotControllerGetStatus>>,
          TError,
          Awaited<ReturnType<typeof iotControllerGetStatus>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useIotControllerGetStatus<
  TData = Awaited<ReturnType<typeof iotControllerGetStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof iotControllerGetStatus>>,
          TError,
          Awaited<ReturnType<typeof iotControllerGetStatus>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useIotControllerGetStatus<
  TData = Awaited<ReturnType<typeof iotControllerGetStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetStatus>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useIotControllerGetStatus<
  TData = Awaited<ReturnType<typeof iotControllerGetStatus>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetStatus>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getIotControllerGetStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const iotControllerGetCurrentWeight = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/iot/scales/weight`, method: 'GET', signal },
    options,
  )
}

export const getIotControllerGetCurrentWeightQueryKey = () => {
  return [`/iot/scales/weight`] as const
}

export const getIotControllerGetCurrentWeightQueryOptions = <
  TData = Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getIotControllerGetCurrentWeightQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>
  > = ({ signal }) => iotControllerGetCurrentWeight(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type IotControllerGetCurrentWeightQueryResult = NonNullable<
  Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>
>
export type IotControllerGetCurrentWeightQueryError = ErrorType<unknown>

export function useIotControllerGetCurrentWeight<
  TData = Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
          TError,
          Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useIotControllerGetCurrentWeight<
  TData = Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
          TError,
          Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useIotControllerGetCurrentWeight<
  TData = Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useIotControllerGetCurrentWeight<
  TData = Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof iotControllerGetCurrentWeight>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getIotControllerGetCurrentWeightQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
