FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./

COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/

COPY . .

RUN npm ci

RUN cd apps/api && npx prisma generate
RUN npx turbo run build --filter=@nutri-sense/api

ENV PORT=3000
EXPOSE 3000

CMD ["node", "apps/api/dist/src/main.js"]
