/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * NutriSense API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CreateTemplateMealFoodDto,
  TemplateMealFoodEntity,
  UpdateTemplateMealFoodDto,
} from '../../model'

import { customInstance } from '../../../lib/axios'
import type { ErrorType } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const templateMealFoodsControllerFindAll = (
  templateMealId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TemplateMealFoodEntity[]>(
    { url: `/templates/meals/${templateMealId}/foods`, method: 'GET', signal },
    options,
  )
}

export const getTemplateMealFoodsControllerFindAllQueryKey = (
  templateMealId: number,
) => {
  return [`/templates/meals/${templateMealId}/foods`] as const
}

export const getTemplateMealFoodsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getTemplateMealFoodsControllerFindAllQueryKey(templateMealId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>
  > = ({ signal }) =>
    templateMealFoodsControllerFindAll(templateMealId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!templateMealId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateMealFoodsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>
>
export type TemplateMealFoodsControllerFindAllQueryError = ErrorType<unknown>

export function useTemplateMealFoodsControllerFindAll<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useTemplateMealFoodsControllerFindAll<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useTemplateMealFoodsControllerFindAll<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useTemplateMealFoodsControllerFindAll<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindAll>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getTemplateMealFoodsControllerFindAllQueryOptions(
    templateMealId,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const templateMealFoodsControllerCreate = (
  templateMealId: number,
  createTemplateMealFoodDto: CreateTemplateMealFoodDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TemplateMealFoodEntity>(
    {
      url: `/templates/meals/${templateMealId}/foods`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTemplateMealFoodDto,
      signal,
    },
    options,
  )
}

export const getTemplateMealFoodsControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof templateMealFoodsControllerCreate>>,
    TError,
    { templateMealId: number; data: CreateTemplateMealFoodDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof templateMealFoodsControllerCreate>>,
  TError,
  { templateMealId: number; data: CreateTemplateMealFoodDto },
  TContext
> => {
  const mutationKey = ['templateMealFoodsControllerCreate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof templateMealFoodsControllerCreate>>,
    { templateMealId: number; data: CreateTemplateMealFoodDto }
  > = (props) => {
    const { templateMealId, data } = props ?? {}

    return templateMealFoodsControllerCreate(
      templateMealId,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type TemplateMealFoodsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof templateMealFoodsControllerCreate>>
>
export type TemplateMealFoodsControllerCreateMutationBody =
  CreateTemplateMealFoodDto
export type TemplateMealFoodsControllerCreateMutationError = ErrorType<unknown>

export const useTemplateMealFoodsControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof templateMealFoodsControllerCreate>>,
      TError,
      { templateMealId: number; data: CreateTemplateMealFoodDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof templateMealFoodsControllerCreate>>,
  TError,
  { templateMealId: number; data: CreateTemplateMealFoodDto },
  TContext
> => {
  return useMutation(
    getTemplateMealFoodsControllerCreateMutationOptions(options),
    queryClient,
  )
}
export const templateMealFoodsControllerFindOne = (
  templateMealId: number,
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TemplateMealFoodEntity>(
    {
      url: `/templates/meals/${templateMealId}/foods/${id}`,
      method: 'GET',
      signal,
    },
    options,
  )
}

export const getTemplateMealFoodsControllerFindOneQueryKey = (
  templateMealId: number,
  id: number,
) => {
  return [`/templates/meals/${templateMealId}/foods/${id}`] as const
}

export const getTemplateMealFoodsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getTemplateMealFoodsControllerFindOneQueryKey(templateMealId, id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>
  > = ({ signal }) =>
    templateMealFoodsControllerFindOne(
      templateMealId,
      id,
      requestOptions,
      signal,
    )

  return {
    queryKey,
    queryFn,
    enabled: !!(templateMealId && id),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TemplateMealFoodsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>
>
export type TemplateMealFoodsControllerFindOneQueryError = ErrorType<unknown>

export function useTemplateMealFoodsControllerFindOne<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useTemplateMealFoodsControllerFindOne<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useTemplateMealFoodsControllerFindOne<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useTemplateMealFoodsControllerFindOne<
  TData = Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  templateMealId: number,
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof templateMealFoodsControllerFindOne>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getTemplateMealFoodsControllerFindOneQueryOptions(
    templateMealId,
    id,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const templateMealFoodsControllerUpdate = (
  templateMealId: number,
  id: number,
  updateTemplateMealFoodDto: UpdateTemplateMealFoodDto,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TemplateMealFoodEntity>(
    {
      url: `/templates/meals/${templateMealId}/foods/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateTemplateMealFoodDto,
      signal,
    },
    options,
  )
}

export const getTemplateMealFoodsControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof templateMealFoodsControllerUpdate>>,
    TError,
    { templateMealId: number; id: number; data: UpdateTemplateMealFoodDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof templateMealFoodsControllerUpdate>>,
  TError,
  { templateMealId: number; id: number; data: UpdateTemplateMealFoodDto },
  TContext
> => {
  const mutationKey = ['templateMealFoodsControllerUpdate']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof templateMealFoodsControllerUpdate>>,
    { templateMealId: number; id: number; data: UpdateTemplateMealFoodDto }
  > = (props) => {
    const { templateMealId, id, data } = props ?? {}

    return templateMealFoodsControllerUpdate(
      templateMealId,
      id,
      data,
      requestOptions,
    )
  }

  return { mutationFn, ...mutationOptions }
}

export type TemplateMealFoodsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof templateMealFoodsControllerUpdate>>
>
export type TemplateMealFoodsControllerUpdateMutationBody =
  UpdateTemplateMealFoodDto
export type TemplateMealFoodsControllerUpdateMutationError = ErrorType<unknown>

export const useTemplateMealFoodsControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof templateMealFoodsControllerUpdate>>,
      TError,
      { templateMealId: number; id: number; data: UpdateTemplateMealFoodDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof templateMealFoodsControllerUpdate>>,
  TError,
  { templateMealId: number; id: number; data: UpdateTemplateMealFoodDto },
  TContext
> => {
  return useMutation(
    getTemplateMealFoodsControllerUpdateMutationOptions(options),
    queryClient,
  )
}
export const templateMealFoodsControllerRemove = (
  templateMealId: number,
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    {
      url: `/templates/meals/${templateMealId}/foods/${id}`,
      method: 'DELETE',
      signal,
    },
    options,
  )
}

export const getTemplateMealFoodsControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof templateMealFoodsControllerRemove>>,
    TError,
    { templateMealId: number; id: number },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof templateMealFoodsControllerRemove>>,
  TError,
  { templateMealId: number; id: number },
  TContext
> => {
  const mutationKey = ['templateMealFoodsControllerRemove']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof templateMealFoodsControllerRemove>>,
    { templateMealId: number; id: number }
  > = (props) => {
    const { templateMealId, id } = props ?? {}

    return templateMealFoodsControllerRemove(templateMealId, id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TemplateMealFoodsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof templateMealFoodsControllerRemove>>
>

export type TemplateMealFoodsControllerRemoveMutationError = ErrorType<unknown>

export const useTemplateMealFoodsControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof templateMealFoodsControllerRemove>>,
      TError,
      { templateMealId: number; id: number },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof templateMealFoodsControllerRemove>>,
  TError,
  { templateMealId: number; id: number },
  TContext
> => {
  return useMutation(
    getTemplateMealFoodsControllerRemoveMutationOptions(options),
    queryClient,
  )
}
