/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedMeasurementsRouteImport } from './routes/_authenticated/measurements'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library/index'
import { Route as AuthenticatedDiaryIndexRouteImport } from './routes/_authenticated/diary/index'
import { Route as AuthenticatedDiaryDateRouteImport } from './routes/_authenticated/diary/$date'
import { Route as AuthenticatedLibraryTemplateMealIdRouteImport } from './routes/_authenticated/library/template-meal/$id'
import { Route as AuthenticatedDiaryMealMealIdRouteImport } from './routes/_authenticated/diary/meal/$mealId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeasurementsRoute =
  AuthenticatedMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiaryIndexRoute = AuthenticatedDiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryDateRoute = AuthenticatedDiaryDateRouteImport.update({
  id: '/diary/$date',
  path: '/diary/$date',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryTemplateMealIdRoute =
  AuthenticatedLibraryTemplateMealIdRouteImport.update({
    id: '/library/template-meal/$id',
    path: '/library/template-meal/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiaryMealMealIdRoute =
  AuthenticatedDiaryMealMealIdRouteImport.update({
    id: '/diary/meal/$mealId',
    path: '/diary/meal/$mealId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/diary/$date': typeof AuthenticatedDiaryDateRoute
  '/diary/': typeof AuthenticatedDiaryIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/diary/meal/$mealId': typeof AuthenticatedDiaryMealMealIdRoute
  '/library/template-meal/$id': typeof AuthenticatedLibraryTemplateMealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/measurements': typeof AuthenticatedMeasurementsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/diary/$date': typeof AuthenticatedDiaryDateRoute
  '/diary': typeof AuthenticatedDiaryIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/diary/meal/$mealId': typeof AuthenticatedDiaryMealMealIdRoute
  '/library/template-meal/$id': typeof AuthenticatedLibraryTemplateMealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/measurements': typeof AuthenticatedMeasurementsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/diary/$date': typeof AuthenticatedDiaryDateRoute
  '/_authenticated/diary/': typeof AuthenticatedDiaryIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/diary/meal/$mealId': typeof AuthenticatedDiaryMealMealIdRoute
  '/_authenticated/library/template-meal/$id': typeof AuthenticatedLibraryTemplateMealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/measurements'
    | '/plans'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/diary/$date'
    | '/diary/'
    | '/library/'
    | '/diary/meal/$mealId'
    | '/library/template-meal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/measurements'
    | '/plans'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/diary/$date'
    | '/diary'
    | '/library'
    | '/diary/meal/$mealId'
    | '/library/template-meal/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/measurements'
    | '/_authenticated/plans'
    | '/_authenticated/settings'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/diary/$date'
    | '/_authenticated/diary/'
    | '/_authenticated/library/'
    | '/_authenticated/diary/meal/$mealId'
    | '/_authenticated/library/template-meal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/measurements': {
      id: '/_authenticated/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof AuthenticatedMeasurementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/': {
      id: '/_authenticated/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof AuthenticatedDiaryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/$date': {
      id: '/_authenticated/diary/$date'
      path: '/diary/$date'
      fullPath: '/diary/$date'
      preLoaderRoute: typeof AuthenticatedDiaryDateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library/template-meal/$id': {
      id: '/_authenticated/library/template-meal/$id'
      path: '/library/template-meal/$id'
      fullPath: '/library/template-meal/$id'
      preLoaderRoute: typeof AuthenticatedLibraryTemplateMealIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/meal/$mealId': {
      id: '/_authenticated/diary/meal/$mealId'
      path: '/diary/meal/$mealId'
      fullPath: '/diary/meal/$mealId'
      preLoaderRoute: typeof AuthenticatedDiaryMealMealIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeasurementsRoute: typeof AuthenticatedMeasurementsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedDiaryDateRoute: typeof AuthenticatedDiaryDateRoute
  AuthenticatedDiaryIndexRoute: typeof AuthenticatedDiaryIndexRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
  AuthenticatedDiaryMealMealIdRoute: typeof AuthenticatedDiaryMealMealIdRoute
  AuthenticatedLibraryTemplateMealIdRoute: typeof AuthenticatedLibraryTemplateMealIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeasurementsRoute: AuthenticatedMeasurementsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedDiaryDateRoute: AuthenticatedDiaryDateRoute,
  AuthenticatedDiaryIndexRoute: AuthenticatedDiaryIndexRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
  AuthenticatedDiaryMealMealIdRoute: AuthenticatedDiaryMealMealIdRoute,
  AuthenticatedLibraryTemplateMealIdRoute:
    AuthenticatedLibraryTemplateMealIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
